### ISSUE TITLE
hardware requirement

### ISSUE THREAD

**Issue by yunruo-zhang-will** [TianheWu/CoSeR#4]
Hi, could someone tell me the hardware requirement for inference?
Thank you!

**Comment by yunruo-zhang-will** [comment]
by the way, which file in 'stabilityai/stable-diffusion-2-1-base' should I use? Really new to this.

**Comment by hjb25286** [comment]
> by the way, which file in 'stabilityai/stable-diffusion-2-1-base' should I use? Really new to this.

Have you solved this problem?

**Comment by kamadosun** [comment]
v2-1_512-ema-pruned.ckpt

**Comment by kamadosun** [comment]
A V100 with 32G memory is enough.

**Comment by yunruo-zhang-will** [comment]
@kamadosun Thank you for replying
