### ISSUE TITLE
How much GPU memory is required to infer on an image?

### ISSUE THREAD

**Issue by Yang-J1225** [TianheWu/CoSeR#5]
How much GPU memory is required to infer on an image?

**Comment by Yang-J1225** [comment]
Apologies for the mistake in my previous message. I encountered this issue when loading the coser model during testing: KeyError: 'model.diffusion_model.time_embed.0.weight'. Could you please let me know which version you are using?

**Comment by YukinoshitaLove** [comment]
![Image](https://github.com/user-attachments/assets/2bef10bd-b9d8-4a47-9287-a0ad8c27331b)
for 128\*128->512\*512
